import React, { FC } from 'react'
import Head from 'next/head'
import HeaderNav from '../HeaderNav/HeaderNav'

import '@fortawesome/fontawesome-svg-core/styles.css'
import style from './MainContainer.module.scss'

const MainContainer: FC = ({ children }) => {
  return (
    <>
      <Head>
        <title>Shopka</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <HeaderNav />

      <div className={style.container}>{children}</div>
    </>
  )
}

export default MainContainer
